export const THUMBNAIL_PIPELINE_MAX_ENTRIES = 2000;
export const THUMBNAIL_PIPELINE_MAX_ACTIVE_IDLE = 6;
export const THUMBNAIL_PIPELINE_MAX_ACTIVE_SCROLL = 3;
export const THUMBNAIL_PIPELINE_MAX_FULL_ACTIVE_IDLE = 1;
export const THUMBNAIL_PIPELINE_MAX_FULL_ACTIVE_SCROLL = 0;
export const THUMBNAIL_PIPELINE_SOURCE_EDGE = 512;
export const THUMBNAIL_PIPELINE_MAX_FULL_LONG_EDGE = 2048;
export const THUMBNAIL_PIPELINE_FULL_QUALITY_THRESHOLD = 0.9;
