import { FAST_TRANSITION_MS } from '../uiTiming';

export const THUMBNAIL_PIPELINE_MAX_ENTRIES = 300;
export const THUMBNAIL_PIPELINE_MAX_VISIBLE_ACTIVE_IDLE = 4;
export const THUMBNAIL_PIPELINE_MAX_VISIBLE_ACTIVE_SLOW = 3;
export const THUMBNAIL_PIPELINE_MAX_VISIBLE_ACTIVE_FAST = 2;
export const THUMBNAIL_PIPELINE_MAX_PREFETCH_ACTIVE_IDLE = 2;
export const THUMBNAIL_PIPELINE_MAX_PREFETCH_ACTIVE_SLOW = 1;
export const THUMBNAIL_PIPELINE_MAX_PREFETCH_ACTIVE_FAST = 0;
export const THUMBNAIL_PIPELINE_MAX_FULL_ACTIVE_IDLE = 5;
export const THUMBNAIL_PIPELINE_MAX_FULL_ACTIVE_SLOW = 4;
export const THUMBNAIL_PIPELINE_MAX_FULL_ACTIVE_FAST = 3;
export const THUMBNAIL_PIPELINE_SOURCE_EDGE = 512;
export const THUMBNAIL_PIPELINE_MAX_FULL_LONG_EDGE = 2048;
export const THUMBNAIL_PIPELINE_FULL_QUALITY_THRESHOLD = 0.9;
export const THUMBNAIL_PIPELINE_REVEAL_MS = FAST_TRANSITION_MS;
