use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct SiteEntry {
    /// Internal identifier (gallery-dl category name).
    pub id: &'static str,
    /// Human-readable display name.
    pub name: &'static str,
    /// Canonical site domain shown in UI and used as credential fallback key.
    pub domain: &'static str,
    /// Site category that owns stored credentials for this source.
    pub credential_owner_site_id: &'static str,
    /// URL template — `{query}` is replaced with the user's search tags.
    pub url_template: &'static str,
    /// Example query to show in the UI.
    pub example_query: &'static str,
    /// Whether this source supports tag/text query style URLs.
    pub supports_query: bool,
    /// Whether account/profile style queries are supported.
    pub supports_account: bool,
    /// Whether we support storing auth material for this source.
    pub auth_supported: bool,
    /// Whether auth is commonly required/recommended for full access.
    pub auth_required_for_full_access: bool,
    /// Whether the site is unusable without credentials — runs are blocked
    /// (not just warned) when no credential is stored.
    pub auth_strictly_required: bool,
    /// Allowed manual credential types for this site.
    pub manual_credential_types: &'static [&'static str],
    /// OAuth provider identifier when the site uses a dedicated OAuth flow.
    pub oauth_provider: Option<&'static str>,
}

const NO_MANUAL_CREDENTIAL_TYPES: &[&str] = &[];
const GENERIC_MANUAL_CREDENTIAL_TYPES: &[&str] =
    &["username_password", "cookies", "api_key", "oauth_token"];
const API_KEY_MANUAL_CREDENTIAL_TYPES: &[&str] = &["api_key"];
const OAUTH_MANUAL_CREDENTIAL_TYPES: &[&str] = &["oauth_token"];

/// Built-in site registry. The user picks one of these; we substitute `{query}`.
pub static SITES: &[SiteEntry] = &[
    SiteEntry {
        id: "pixiv",
        domain: "pixiv.net",
        credential_owner_site_id: "pixiv",
        name: "Pixiv",
        url_template: "https://www.pixiv.net/en/tags/{query}/artworks?s_mode=s_tag",
        example_query: "風景",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: true,
        manual_credential_types: OAUTH_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: Some("pixiv"),
    },
    SiteEntry {
        id: "pixivuser",
        domain: "pixiv.net",
        credential_owner_site_id: "pixiv",
        name: "Pixiv (user)",
        url_template: "https://www.pixiv.net/en/users/{query}",
        example_query: "12345",
        supports_query: false,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: Some("pixiv"),
    },
    SiteEntry {
        id: "gelbooru",
        domain: "gelbooru.com",
        credential_owner_site_id: "gelbooru",
        name: "Gelbooru",
        url_template: "https://gelbooru.com/index.php?page=post&s=list&tags={query}",
        example_query: "1girl solo",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: API_KEY_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "danbooru",
        domain: "danbooru.donmai.us",
        credential_owner_site_id: "danbooru",
        name: "Danbooru",
        url_template: "https://danbooru.donmai.us/posts?tags={query}",
        // Anonymous danbooru searches allow at most 2 tags (more requires Gold).
        example_query: "1girl solo",
        supports_query: true,
        supports_account: false,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    // 3dbooru (behoimi.org) removed 2026-07: host unreachable (connection
    // timeout on http/https, 100% packet loss) — site appears dead.
    SiteEntry {
        id: "artstation",
        domain: "artstation.com",
        credential_owner_site_id: "artstation",
        name: "ArtStation",
        url_template: "https://www.artstation.com/{query}",
        example_query: "username",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "sankaku",
        domain: "sankakucomplex.com",
        credential_owner_site_id: "sankaku",
        name: "Sankaku",
        url_template: "https://chan.sankakucomplex.com/?tags={query}&commit=Search",
        example_query: "1girl",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "idolcomplex",
        domain: "idol.sankakucomplex.com",
        credential_owner_site_id: "idolcomplex",
        name: "IdolComplex",
        url_template: "https://idol.sankakucomplex.com/?tags={query}&commit=Search",
        example_query: "idol",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "twitter",
        domain: "twitter.com",
        credential_owner_site_id: "twitter",
        name: "Twitter/X",
        url_template: "https://twitter.com/{query}",
        example_query: "username",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "deviantart",
        domain: "deviantart.com",
        credential_owner_site_id: "deviantart",
        name: "DeviantArt",
        url_template: "https://deviantart.com/{query}",
        example_query: "username",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "patreon",
        domain: "patreon.com",
        credential_owner_site_id: "patreon",
        name: "Patreon",
        url_template: "https://www.patreon.com/{query}/posts",
        example_query: "creatorname",
        supports_query: false,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: true,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "nijie",
        domain: "nijie.info",
        credential_owner_site_id: "nijie",
        name: "Nijie",
        url_template: "https://nijie.info/members_illust.php?id={query}",
        example_query: "12345",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: true,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "tumblr",
        domain: "tumblr.com",
        credential_owner_site_id: "tumblr",
        name: "Tumblr",
        url_template: "https://{query}.tumblr.com",
        example_query: "blogname",
        supports_query: true,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "fantia",
        domain: "fantia.jp",
        credential_owner_site_id: "fantia",
        name: "Fantia",
        url_template: "https://fantia.jp/fanclubs/{query}/posts",
        example_query: "12345",
        supports_query: false,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: true,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "fanbox",
        domain: "fanbox.cc",
        credential_owner_site_id: "fanbox",
        name: "Fanbox",
        url_template: "https://{query}.fanbox.cc",
        example_query: "creatorname",
        supports_query: false,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: true,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "webtoons",
        domain: "webtoons.com",
        credential_owner_site_id: "webtoons",
        name: "Webtoons",
        url_template: "https://www.webtoons.com/en/{query}",
        example_query: "genre/title/list?title_no=12345",
        supports_query: false,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    // kemono (kemono.cr) removed 2026-07: file servers down since ~April 2026,
    // site serves previews only and is likely dying. Pawchive is the replacement.
    SiteEntry {
        id: "coomer",
        domain: "coomer.st",
        credential_owner_site_id: "coomer",
        name: "Coomer",
        url_template: "https://coomer.st/{query}",
        example_query: "onlyfans/user/12345",
        supports_query: false,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "pawchive",
        domain: "pawchive.pw",
        credential_owner_site_id: "pawchive",
        name: "Pawchive",
        url_template: "https://pawchive.pw/{query}",
        example_query: "patreon/user/12345",
        supports_query: false,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "baraag",
        domain: "baraag.net",
        credential_owner_site_id: "baraag",
        name: "Baraag",
        url_template: "https://baraag.net/{query}",
        example_query: "@username",
        supports_query: false,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "pawoo",
        domain: "pawoo.net",
        credential_owner_site_id: "pawoo",
        name: "Pawoo",
        url_template: "https://pawoo.net/{query}",
        example_query: "@username",
        supports_query: false,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "hentaifoundry",
        domain: "hentai-foundry.com",
        credential_owner_site_id: "hentaifoundry",
        name: "Hentai Foundry",
        // Account-style template — the "query" is a username, not search tags.
        url_template: "https://www.hentai-foundry.com/user/{query}/profile",
        example_query: "username",
        supports_query: false,
        supports_account: true,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "yandere",
        domain: "yande.re",
        credential_owner_site_id: "yandere",
        name: "Yande.re",
        url_template: "https://yande.re/post?tags={query}",
        example_query: "landscape",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "rule34",
        domain: "rule34.xxx",
        credential_owner_site_id: "rule34",
        name: "Rule34.xxx",
        url_template: "https://rule34.xxx/index.php?page=post&s=list&tags={query}",
        example_query: "solo",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: API_KEY_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "e621",
        domain: "e621.net",
        credential_owner_site_id: "e621",
        name: "e621",
        url_template: "https://e621.net/posts?tags={query}",
        example_query: "solo canine rating:safe",
        supports_query: true,
        supports_account: false,
        auth_supported: false,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: NO_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "furaffinity",
        domain: "furaffinity.net",
        credential_owner_site_id: "furaffinity",
        name: "FurAffinity",
        url_template: "https://www.furaffinity.net/user/{query}/",
        example_query: "username",
        supports_query: false,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "instagram",
        domain: "instagram.com",
        credential_owner_site_id: "instagram",
        name: "Instagram",
        url_template: "https://instagram.com/{query}",
        example_query: "username",
        supports_query: false,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: true,
        auth_strictly_required: true,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    // Existing maintained extras.
    SiteEntry {
        id: "konachan",
        domain: "konachan.com",
        credential_owner_site_id: "konachan",
        name: "Konachan",
        url_template: "https://konachan.com/post?tags={query}",
        example_query: "landscape",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
    SiteEntry {
        id: "safebooru",
        domain: "safebooru.org",
        credential_owner_site_id: "safebooru",
        name: "Safebooru",
        url_template: "https://safebooru.org/index.php?page=post&s=list&tags={query}",
        example_query: "1girl smile",
        supports_query: true,
        supports_account: true,
        auth_supported: true,
        auth_required_for_full_access: false,
        auth_strictly_required: false,
        manual_credential_types: GENERIC_MANUAL_CREDENTIAL_TYPES,
        oauth_provider: None,
    },
];

/// Canonicalize legacy/alias site ids to current internal ids.
pub fn canonical_site_id(id: &str) -> &str {
    match id {
        "rule34xxx" | "rule34.xxx" => "rule34",
        "e621.net" => "e621",
        "furaffinity.net" => "furaffinity",
        "yande.re" => "yandere",
        "kemono.party" | "kemono.su" | "kemonoparty" => "kemono",
        "coomer.party" | "coomer.su" | "comerparty" | "coomerparty" => "coomer",
        "pawchive.pw" | "pawchive.st" => "pawchive",
        "baraag.net" => "baraag",
        "pawoo.net" => "pawoo",
        _ => id,
    }
}

pub fn credential_site_aliases(id: &str) -> &'static [&'static str] {
    match canonical_site_id(id) {
        "rule34" => &["rule34xxx", "rule34.xxx"],
        "e621" => &["e621.net"],
        "furaffinity" => &["furaffinity.net"],
        "yandere" => &["yande.re"],
        "kemono" => &["kemono.party", "kemono.su", "kemonoparty"],
        "coomer" => &["coomer.party", "coomer.su", "comerparty", "coomerparty"],
        "pawchive" => &["pawchive.pw", "pawchive.st"],
        "baraag" => &["baraag.net"],
        "pawoo" => &["pawoo.net"],
        _ => &[],
    }
}

/// Look up a site entry by ID.
pub fn site_by_id(id: &str) -> Option<&'static SiteEntry> {
    let canonical = canonical_site_id(id);
    SITES.iter().find(|s| s.id == canonical)
}

/// Build a full URL from a site ID and query string.
pub fn build_url(site_id: &str, query: &str) -> Option<String> {
    site_by_id(site_id).map(|site| substitute_query(site.url_template, query))
}

pub fn substitute_query(template: &str, query: &str) -> String {
    template.replace("{query}", query)
}

/// Extract the domain from a URL for rate limiting / credential lookup.
pub fn extract_domain(url_str: &str) -> Option<String> {
    url::Url::parse(url_str)
        .ok()
        .and_then(|u| u.host_str().map(String::from))
}
