/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Put physical files on the operating-system clipboard. */
export declare function copyFiles(filePaths: Array<string>): boolean
export declare function getAssociatedApplications(filePath: string): Promise<string>
export declare function openWithApplication(applicationPath: string, filePath: string): void
/** Apply a persistent custom Finder icon to a file or package on macOS. */
export declare function setFileIcon(iconPath: string, filePath: string): boolean
/**
 * Start a native file drag on macOS with a single composite icon.
 * On non-macOS platforms this is a no-op (use Electron's startDrag instead).
 */
export declare function startNativeDrag(windowHandle: Buffer, filePaths: Array<string>, iconRgba: Buffer, iconWidth: number, iconHeight: number): void
/** Initialize tracing and runtime. Called once at process startup. */
export declare function initRuntime(applicationDataRoot: string): void
export declare function healthcheck(): Promise<string>
/** Open a library at the given path. Closes any previously open library first. */
export declare function openLibrary(libraryPath: string): Promise<void>
/** Open an isolated tutorial library backed only by bundled local fixtures. */
export declare function openTutorialLibrary(libraryPath: string, fixtureRoot: string): Promise<void>
/** Close the currently open library, stopping all background tasks. */
export declare function closeLibrary(): Promise<void>
/**
 * Dispatch a command to the core engine.
 * `command` is the command name, `args_json` is a JSON-encoded arguments object.
 * Returns a JSON-encoded result string.
 */
export declare function invoke(command: string, argsJson: string): Promise<string>
/**
 * Register a callback that receives native events from the core engine.
 * The callback receives (event_name: string, payload_json: string).
 */
export declare function registerEventCallback(callback: (...args: any[]) => any): void
export declare function emitTestEvent(name: string, payloadJson: string): void
