/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function healthcheck(): Promise<string>
/** Open a library at the given path. Closes any previously open library first. */
export declare function openLibrary(libraryPath: string): Promise<void>
/** Backward-compatible alias for `open_library`. */
export declare function initialize(libraryPath: string): Promise<void>
/** Close the currently open library, stopping all background tasks. */
export declare function closeLibrary(): Promise<void>
/**
 * Dispatch a command to the core engine.
 * `command` is the command name, `args_json` is a JSON-encoded arguments object.
 * Returns a JSON-encoded result string.
 */
export declare function invoke(command: string, argsJson: string): Promise<string>
/**
 * Register a callback that receives native events from the core engine.
 * The callback receives (event_name: string, payload_json: string).
 */
export declare function registerEventCallback(callback: (...args: any[]) => any): void
export declare function emitTestEvent(name: string, payloadJson: string): void
