/**
 * Curated icon registry — same icons as legacy, used by IconPicker.
 * Also used by DynamicIcon for runtime icon name → component lookup.
 */

import type { Icon as TablerIcon } from '@tabler/icons-react';
import {
  IconPhoto, IconVideo, IconMusic, IconCamera, IconPlayerPlay, IconMicrophone,
  IconHeadphones, IconVolume, IconScreenShare, IconBrandYoutube,
  IconFile, IconFileText, IconFolder, IconFolderOpen, IconArchive, IconClipboard,
  IconNote, IconBook, IconNotebook, IconFileZip,
  IconSquare, IconCircle, IconTriangle, IconHexagon, IconDiamond, IconStar,
  IconHeart, IconSparkles,
  IconHome, IconBuildingSkyscraper, IconCar, IconPlane, IconRocket, IconAnchor,
  IconCompass, IconMap, IconGlobe, IconFlag,
  IconSun, IconMoon, IconCloud, IconSnowflake, IconDroplet, IconFlame,
  IconLeaf, IconTree, IconMountain, IconWind,
  IconDog, IconCat, IconFish, IconBug, IconFeather, IconPaw,
  IconUser, IconUsers, IconUserCircle, IconMoodSmile, IconMoodHappy, IconFriends,
  IconMan, IconWoman, IconAccessible,
  IconMail, IconMessage, IconBell, IconPhone, IconBrandTwitter, IconBrandInstagram,
  IconSend, IconAt, IconHash, IconBrandDiscord,
  IconPalette, IconBrush, IconPencil, IconHighlight, IconScissors, IconRuler,
  IconColorSwatch, IconWand, IconSpray,
  IconCode, IconTerminal, IconDatabase, IconServer, IconCpu, IconWifi,
  IconBluetooth, IconDeviceDesktop, IconDeviceMobile, IconBrandGithub,
  IconTag, IconBookmark, IconPin, IconLock, IconShield, IconEye,
  IconClock, IconCalendar, IconGift, IconTrophy,
  IconCrown, IconBolt, IconTarget, IconPuzzle, IconDice, IconChess,
  IconAward, IconCoffee, IconPizza, IconApple,
} from '@tabler/icons-react';
import { IconPersonSimple, IconPersonMale, IconPersonFemale } from './customIcons';
import { t } from '../../../i18n';

export interface CuratedIcon {
  name: string;
  label: string;
  component: TablerIcon;
}

export const CURATED_ICONS: CuratedIcon[] = [
  { name: 'IconPhoto', label: t("Photo"), component: IconPhoto },
  { name: 'IconVideo', label: t("Video"), component: IconVideo },
  { name: 'IconMusic', label: t("Music"), component: IconMusic },
  { name: 'IconCamera', label: t("Camera"), component: IconCamera },
  { name: 'IconPlayerPlay', label: t("Play"), component: IconPlayerPlay },
  { name: 'IconMicrophone', label: t("Microphone"), component: IconMicrophone },
  { name: 'IconHeadphones', label: t("Headphones"), component: IconHeadphones },
  { name: 'IconVolume', label: t("Volume"), component: IconVolume },
  { name: 'IconScreenShare', label: t("Screen"), component: IconScreenShare },
  { name: 'IconBrandYoutube', label: t("YouTube"), component: IconBrandYoutube },
  { name: 'IconFile', label: t("File"), component: IconFile },
  { name: 'IconFileText', label: t("Text File"), component: IconFileText },
  { name: 'IconFolder', label: t("Folder"), component: IconFolder },
  { name: 'IconFolderOpen', label: t("Open Folder"), component: IconFolderOpen },
  { name: 'IconArchive', label: t("Archive"), component: IconArchive },
  { name: 'IconClipboard', label: t("Clipboard"), component: IconClipboard },
  { name: 'IconNote', label: t("Note"), component: IconNote },
  { name: 'IconBook', label: t("Book"), component: IconBook },
  { name: 'IconNotebook', label: t("Notebook"), component: IconNotebook },
  { name: 'IconFileZip', label: t("Zip"), component: IconFileZip },
  { name: 'IconSquare', label: t("Square"), component: IconSquare },
  { name: 'IconCircle', label: t("Circle"), component: IconCircle },
  { name: 'IconTriangle', label: t("Triangle"), component: IconTriangle },
  { name: 'IconHexagon', label: t("Hexagon"), component: IconHexagon },
  { name: 'IconDiamond', label: t("Diamond"), component: IconDiamond },
  { name: 'IconStar', label: t("Star"), component: IconStar },
  { name: 'IconHeart', label: t("Heart"), component: IconHeart },
  { name: 'IconSparkles', label: t("Sparkles"), component: IconSparkles },
  { name: 'IconHome', label: t("Home"), component: IconHome },
  { name: 'IconBuildingSkyscraper', label: t("Building"), component: IconBuildingSkyscraper },
  { name: 'IconCar', label: t("Car"), component: IconCar },
  { name: 'IconPlane', label: t("Plane"), component: IconPlane },
  { name: 'IconRocket', label: t("Rocket"), component: IconRocket },
  { name: 'IconAnchor', label: t("Anchor"), component: IconAnchor },
  { name: 'IconCompass', label: t("Compass"), component: IconCompass },
  { name: 'IconMap', label: t("Map"), component: IconMap },
  { name: 'IconGlobe', label: t("Globe"), component: IconGlobe },
  { name: 'IconFlag', label: t("Flag"), component: IconFlag },
  { name: 'IconSun', label: t("Sun"), component: IconSun },
  { name: 'IconMoon', label: t("Moon"), component: IconMoon },
  { name: 'IconCloud', label: t("Cloud"), component: IconCloud },
  { name: 'IconSnowflake', label: t("Snowflake"), component: IconSnowflake },
  { name: 'IconDroplet', label: t("Droplet"), component: IconDroplet },
  { name: 'IconFlame', label: t("Flame"), component: IconFlame },
  { name: 'IconLeaf', label: t("Leaf"), component: IconLeaf },
  { name: 'IconTree', label: t("Tree"), component: IconTree },
  { name: 'IconMountain', label: t("Mountain"), component: IconMountain },
  { name: 'IconWind', label: t("Wind"), component: IconWind },
  { name: 'IconDog', label: t("Dog"), component: IconDog },
  { name: 'IconCat', label: t("Cat"), component: IconCat },
  { name: 'IconFish', label: t("Fish"), component: IconFish },
  { name: 'IconBug', label: t("Bug"), component: IconBug },
  { name: 'IconFeather', label: t("Feather"), component: IconFeather },
  { name: 'IconPaw', label: t("Paw"), component: IconPaw },
  { name: 'IconUser', label: t("User"), component: IconUser },
  { name: 'IconUsers', label: t("Users"), component: IconUsers },
  { name: 'IconUserCircle', label: t("User Circle"), component: IconUserCircle },
  { name: 'IconMoodSmile', label: t("Smile"), component: IconMoodSmile },
  { name: 'IconMoodHappy', label: t("Happy"), component: IconMoodHappy },
  { name: 'IconFriends', label: t("Friends"), component: IconFriends },
  { name: 'IconMan', label: t("Man"), component: IconMan },
  { name: 'IconWoman', label: t("Woman"), component: IconWoman },
  { name: 'IconAccessible', label: t("Accessible"), component: IconAccessible },
  { name: 'IconMail', label: t("Mail"), component: IconMail },
  { name: 'IconMessage', label: t("Message"), component: IconMessage },
  { name: 'IconBell', label: t("Bell"), component: IconBell },
  { name: 'IconPhone', label: t("Phone"), component: IconPhone },
  { name: 'IconBrandTwitter', label: t("Twitter"), component: IconBrandTwitter },
  { name: 'IconBrandInstagram', label: t("Instagram"), component: IconBrandInstagram },
  { name: 'IconSend', label: t("Send"), component: IconSend },
  { name: 'IconAt', label: t("At"), component: IconAt },
  { name: 'IconHash', label: t("Hash"), component: IconHash },
  { name: 'IconBrandDiscord', label: t("Discord"), component: IconBrandDiscord },
  { name: 'IconPalette', label: t("Palette"), component: IconPalette },
  { name: 'IconBrush', label: t("Brush"), component: IconBrush },
  { name: 'IconPencil', label: t("Pencil"), component: IconPencil },
  { name: 'IconHighlight', label: t("Highlight"), component: IconHighlight },
  { name: 'IconScissors', label: t("Scissors"), component: IconScissors },
  { name: 'IconRuler', label: t("Ruler"), component: IconRuler },
  { name: 'IconColorSwatch', label: t("Color Swatch"), component: IconColorSwatch },
  { name: 'IconWand', label: t("Wand"), component: IconWand },
  { name: 'IconSpray', label: t("Spray"), component: IconSpray },
  { name: 'IconCode', label: t("Code"), component: IconCode },
  { name: 'IconTerminal', label: t("Terminal"), component: IconTerminal },
  { name: 'IconDatabase', label: t("Database"), component: IconDatabase },
  { name: 'IconServer', label: t("Server"), component: IconServer },
  { name: 'IconCpu', label: t("CPU"), component: IconCpu },
  { name: 'IconWifi', label: t("WiFi"), component: IconWifi },
  { name: 'IconBluetooth', label: t("Bluetooth"), component: IconBluetooth },
  { name: 'IconDeviceDesktop', label: t("Desktop"), component: IconDeviceDesktop },
  { name: 'IconDeviceMobile', label: t("Mobile"), component: IconDeviceMobile },
  { name: 'IconBrandGithub', label: t("GitHub"), component: IconBrandGithub },
  { name: 'IconTag', label: t("Tag"), component: IconTag },
  { name: 'IconBookmark', label: t("Bookmark"), component: IconBookmark },
  { name: 'IconPin', label: t("Pin"), component: IconPin },
  { name: 'IconLock', label: t("Lock"), component: IconLock },
  { name: 'IconShield', label: t("Shield"), component: IconShield },
  { name: 'IconEye', label: t("Eye"), component: IconEye },
  { name: 'IconClock', label: t("Clock"), component: IconClock },
  { name: 'IconCalendar', label: t("Calendar"), component: IconCalendar },
  { name: 'IconGift', label: t("Gift"), component: IconGift },
  { name: 'IconTrophy', label: t("Trophy"), component: IconTrophy },
  { name: 'IconCrown', label: t("Crown"), component: IconCrown },
  { name: 'IconBolt', label: t("Bolt"), component: IconBolt },
  { name: 'IconTarget', label: t("Target"), component: IconTarget },
  { name: 'IconPuzzle', label: t("Puzzle"), component: IconPuzzle },
  { name: 'IconDice', label: t("Dice"), component: IconDice },
  { name: 'IconChess', label: t("Chess"), component: IconChess },
  { name: 'IconAward', label: t("Award"), component: IconAward },
  { name: 'IconCoffee', label: t("Coffee"), component: IconCoffee },
  { name: 'IconPizza', label: t("Pizza"), component: IconPizza },
  { name: 'IconApple', label: t("Apple"), component: IconApple },
  { name: 'IconPersonSimple', label: t("Person"), component: IconPersonSimple as unknown as TablerIcon },
  { name: 'IconPersonMale', label: t("Male"), component: IconPersonMale as unknown as TablerIcon },
  { name: 'IconPersonFemale', label: t("Female"), component: IconPersonFemale as unknown as TablerIcon },
];

export const ICON_MAP = new Map(CURATED_ICONS.map((i) => [i.name, i.component]));
