/**
 * Curated icon registry — same icons as legacy, used by IconPicker.
 * Also used by DynamicIcon for runtime icon name → component lookup.
 */

import type { Icon as TablerIcon } from '@tabler/icons-react';
import {
  IconPhoto, IconVideo, IconMusic, IconCamera, IconPlayerPlay, IconMicrophone,
  IconHeadphones, IconVolume, IconScreenShare, IconBrandYoutube,
  IconFile, IconFileText, IconFolder, IconFolderOpen, IconArchive, IconClipboard,
  IconNote, IconBook, IconNotebook, IconFileZip,
  IconSquare, IconCircle, IconTriangle, IconHexagon, IconDiamond, IconStar,
  IconHeart, IconStarFilled, IconHeartFilled, IconSparkles,
  IconHome, IconBuildingSkyscraper, IconCar, IconPlane, IconRocket, IconAnchor,
  IconCompass, IconMap, IconGlobe, IconFlag,
  IconSun, IconMoon, IconCloud, IconSnowflake, IconDroplet, IconFlame,
  IconLeaf, IconTree, IconMountain, IconWind,
  IconDog, IconCat, IconFish, IconBug, IconFeather, IconPaw,
  IconUser, IconUsers, IconUserCircle, IconMoodSmile, IconMoodHappy, IconFriends,
  IconMan, IconWoman, IconAccessible,
  IconMail, IconMessage, IconBell, IconPhone, IconBrandTwitter, IconBrandInstagram,
  IconSend, IconAt, IconHash, IconBrandDiscord,
  IconPalette, IconBrush, IconPencil, IconHighlight, IconScissors, IconRuler,
  IconColorSwatch, IconDropletFilled, IconWand, IconSpray,
  IconCode, IconTerminal, IconDatabase, IconServer, IconCpu, IconWifi,
  IconBluetooth, IconDeviceDesktop, IconDeviceMobile, IconBrandGithub,
  IconTag, IconBookmark, IconPin, IconLock, IconShield, IconEye,
  IconClock, IconCalendar, IconGift, IconTrophy,
  IconCrown, IconBolt, IconTarget, IconPuzzle, IconDice, IconChess,
  IconAward, IconCoffee, IconPizza, IconApple,
} from '@tabler/icons-react';

export interface CuratedIcon {
  name: string;
  label: string;
  component: TablerIcon;
}

export const CURATED_ICONS: CuratedIcon[] = [
  { name: 'IconPhoto', label: 'Photo', component: IconPhoto },
  { name: 'IconVideo', label: 'Video', component: IconVideo },
  { name: 'IconMusic', label: 'Music', component: IconMusic },
  { name: 'IconCamera', label: 'Camera', component: IconCamera },
  { name: 'IconPlayerPlay', label: 'Play', component: IconPlayerPlay },
  { name: 'IconMicrophone', label: 'Microphone', component: IconMicrophone },
  { name: 'IconHeadphones', label: 'Headphones', component: IconHeadphones },
  { name: 'IconVolume', label: 'Volume', component: IconVolume },
  { name: 'IconScreenShare', label: 'Screen', component: IconScreenShare },
  { name: 'IconBrandYoutube', label: 'YouTube', component: IconBrandYoutube },
  { name: 'IconFile', label: 'File', component: IconFile },
  { name: 'IconFileText', label: 'Text File', component: IconFileText },
  { name: 'IconFolder', label: 'Folder', component: IconFolder },
  { name: 'IconFolderOpen', label: 'Open Folder', component: IconFolderOpen },
  { name: 'IconArchive', label: 'Archive', component: IconArchive },
  { name: 'IconClipboard', label: 'Clipboard', component: IconClipboard },
  { name: 'IconNote', label: 'Note', component: IconNote },
  { name: 'IconBook', label: 'Book', component: IconBook },
  { name: 'IconNotebook', label: 'Notebook', component: IconNotebook },
  { name: 'IconFileZip', label: 'Zip', component: IconFileZip },
  { name: 'IconSquare', label: 'Square', component: IconSquare },
  { name: 'IconCircle', label: 'Circle', component: IconCircle },
  { name: 'IconTriangle', label: 'Triangle', component: IconTriangle },
  { name: 'IconHexagon', label: 'Hexagon', component: IconHexagon },
  { name: 'IconDiamond', label: 'Diamond', component: IconDiamond },
  { name: 'IconStar', label: 'Star', component: IconStar },
  { name: 'IconHeart', label: 'Heart', component: IconHeart },
  { name: 'IconStarFilled', label: 'Star Filled', component: IconStarFilled },
  { name: 'IconHeartFilled', label: 'Heart Filled', component: IconHeartFilled },
  { name: 'IconSparkles', label: 'Sparkles', component: IconSparkles },
  { name: 'IconHome', label: 'Home', component: IconHome },
  { name: 'IconBuildingSkyscraper', label: 'Building', component: IconBuildingSkyscraper },
  { name: 'IconCar', label: 'Car', component: IconCar },
  { name: 'IconPlane', label: 'Plane', component: IconPlane },
  { name: 'IconRocket', label: 'Rocket', component: IconRocket },
  { name: 'IconAnchor', label: 'Anchor', component: IconAnchor },
  { name: 'IconCompass', label: 'Compass', component: IconCompass },
  { name: 'IconMap', label: 'Map', component: IconMap },
  { name: 'IconGlobe', label: 'Globe', component: IconGlobe },
  { name: 'IconFlag', label: 'Flag', component: IconFlag },
  { name: 'IconSun', label: 'Sun', component: IconSun },
  { name: 'IconMoon', label: 'Moon', component: IconMoon },
  { name: 'IconCloud', label: 'Cloud', component: IconCloud },
  { name: 'IconSnowflake', label: 'Snowflake', component: IconSnowflake },
  { name: 'IconDroplet', label: 'Droplet', component: IconDroplet },
  { name: 'IconFlame', label: 'Flame', component: IconFlame },
  { name: 'IconLeaf', label: 'Leaf', component: IconLeaf },
  { name: 'IconTree', label: 'Tree', component: IconTree },
  { name: 'IconMountain', label: 'Mountain', component: IconMountain },
  { name: 'IconWind', label: 'Wind', component: IconWind },
  { name: 'IconDog', label: 'Dog', component: IconDog },
  { name: 'IconCat', label: 'Cat', component: IconCat },
  { name: 'IconFish', label: 'Fish', component: IconFish },
  { name: 'IconBug', label: 'Bug', component: IconBug },
  { name: 'IconFeather', label: 'Feather', component: IconFeather },
  { name: 'IconPaw', label: 'Paw', component: IconPaw },
  { name: 'IconUser', label: 'User', component: IconUser },
  { name: 'IconUsers', label: 'Users', component: IconUsers },
  { name: 'IconUserCircle', label: 'User Circle', component: IconUserCircle },
  { name: 'IconMoodSmile', label: 'Smile', component: IconMoodSmile },
  { name: 'IconMoodHappy', label: 'Happy', component: IconMoodHappy },
  { name: 'IconFriends', label: 'Friends', component: IconFriends },
  { name: 'IconMan', label: 'Man', component: IconMan },
  { name: 'IconWoman', label: 'Woman', component: IconWoman },
  { name: 'IconAccessible', label: 'Accessible', component: IconAccessible },
  { name: 'IconMail', label: 'Mail', component: IconMail },
  { name: 'IconMessage', label: 'Message', component: IconMessage },
  { name: 'IconBell', label: 'Bell', component: IconBell },
  { name: 'IconPhone', label: 'Phone', component: IconPhone },
  { name: 'IconBrandTwitter', label: 'Twitter', component: IconBrandTwitter },
  { name: 'IconBrandInstagram', label: 'Instagram', component: IconBrandInstagram },
  { name: 'IconSend', label: 'Send', component: IconSend },
  { name: 'IconAt', label: 'At', component: IconAt },
  { name: 'IconHash', label: 'Hash', component: IconHash },
  { name: 'IconBrandDiscord', label: 'Discord', component: IconBrandDiscord },
  { name: 'IconPalette', label: 'Palette', component: IconPalette },
  { name: 'IconBrush', label: 'Brush', component: IconBrush },
  { name: 'IconPencil', label: 'Pencil', component: IconPencil },
  { name: 'IconHighlight', label: 'Highlight', component: IconHighlight },
  { name: 'IconScissors', label: 'Scissors', component: IconScissors },
  { name: 'IconRuler', label: 'Ruler', component: IconRuler },
  { name: 'IconColorSwatch', label: 'Color Swatch', component: IconColorSwatch },
  { name: 'IconDropletFilled', label: 'Ink Drop', component: IconDropletFilled },
  { name: 'IconWand', label: 'Wand', component: IconWand },
  { name: 'IconSpray', label: 'Spray', component: IconSpray },
  { name: 'IconCode', label: 'Code', component: IconCode },
  { name: 'IconTerminal', label: 'Terminal', component: IconTerminal },
  { name: 'IconDatabase', label: 'Database', component: IconDatabase },
  { name: 'IconServer', label: 'Server', component: IconServer },
  { name: 'IconCpu', label: 'CPU', component: IconCpu },
  { name: 'IconWifi', label: 'WiFi', component: IconWifi },
  { name: 'IconBluetooth', label: 'Bluetooth', component: IconBluetooth },
  { name: 'IconDeviceDesktop', label: 'Desktop', component: IconDeviceDesktop },
  { name: 'IconDeviceMobile', label: 'Mobile', component: IconDeviceMobile },
  { name: 'IconBrandGithub', label: 'GitHub', component: IconBrandGithub },
  { name: 'IconTag', label: 'Tag', component: IconTag },
  { name: 'IconBookmark', label: 'Bookmark', component: IconBookmark },
  { name: 'IconPin', label: 'Pin', component: IconPin },
  { name: 'IconLock', label: 'Lock', component: IconLock },
  { name: 'IconShield', label: 'Shield', component: IconShield },
  { name: 'IconEye', label: 'Eye', component: IconEye },
  { name: 'IconClock', label: 'Clock', component: IconClock },
  { name: 'IconCalendar', label: 'Calendar', component: IconCalendar },
  { name: 'IconGift', label: 'Gift', component: IconGift },
  { name: 'IconTrophy', label: 'Trophy', component: IconTrophy },
  { name: 'IconCrown', label: 'Crown', component: IconCrown },
  { name: 'IconBolt', label: 'Bolt', component: IconBolt },
  { name: 'IconTarget', label: 'Target', component: IconTarget },
  { name: 'IconPuzzle', label: 'Puzzle', component: IconPuzzle },
  { name: 'IconDice', label: 'Dice', component: IconDice },
  { name: 'IconChess', label: 'Chess', component: IconChess },
  { name: 'IconAward', label: 'Award', component: IconAward },
  { name: 'IconCoffee', label: 'Coffee', component: IconCoffee },
  { name: 'IconPizza', label: 'Pizza', component: IconPizza },
  { name: 'IconApple', label: 'Apple', component: IconApple },
];

export const ICON_MAP = new Map(CURATED_ICONS.map((i) => [i.name, i.component]));
